### ISSUE TITLE
Update to 3366

### ISSUE THREAD

**Issue by SourcePowered** [Sh1ft0x0EF/Xash3DEx#1]
Hello! Sir! I used your engine a long time(I am a half life mapper).
But can you update it to 3366 version?
Thanks!!!

**Comment by Sh1ft0x0EF** [comment]
Hello! I didn't expect that this version still used by someone.
Sure can.

**Comment by SourcePowered** [comment]
Thank you so much! Sir!
The reasons for my continued use of this version:
1. It is very easy to compile, beyond all the current version (the original projects is VC6.0...... It is really..........Hard...);
2. Didn't add too much for me (I'm a mapper, I don't need too many functions, like, SDL?!);
3. There are a lot of benefits for me, I can not express;
So please update as soon as possible! I still have a lot of friends who are using your version(They are all mapper)!

**Comment by Sh1ft0x0EF** [comment]
Wow! Thank you too, it's a pleasure to know that
Engine is already merged with 3366 laying on my local branch for some time, but it currently needs some clean up, stabilization and build-test

**Comment by SourcePowered** [comment]
OK! Sir! I am looking forward to it!!!

**Comment by Sh1ft0x0EF** [comment]
Well
I compiled it and now it needs testing
I'd be glad if you could help me with that if you have VC2015 redist installed
I will try to recompile it to use msvcrt.dll, but now we have only vs15 version compiled (and hopefully running)
Sorry, I can't test it myself

**Comment by Sh1ft0x0EF** [comment]
Done
