### ISSUE TITLE
Console option not showing up in menu

### ISSUE THREAD

**Issue by CrusoeDaWolf** [Sh1ft0x0EF/Xash3DEx#14]
I'm trying to launch Xash3DEx with the console. I have a batch file with the -console parameter but console does not show up. I have made sure that inside gameinfo.txt that "secure" is removed. How do I get the console to show up?

**Comment by Sh1ft0x0EF** [comment]
Aye, it's kinda strange, but currently console opens after map load
As I remember you can open it by Console button in menu. Or it was ripped off already...
Standard tilde "~" button should work but currently only after you load a map using the menu
I will try to search and find out what's the problem

**Comment by CrusoeDaWolf** [comment]
Alright. Thanks.

**Comment by Sh1ft0x0EF** [comment]
So now console opens with any dev level but renders only if dev > 0 (blank screen instead with dev 0)

**Comment by Sh1ft0x0EF** [comment]
https://github.com/Sh1ft0x0EF/Xash3DEx/releases/tag/0.98b3412
Here, try it out
But you need to start with "-dev" > 0 because console is still buggy and draws only at dev level >= 1

**Comment by CrusoeDaWolf** [comment]
Alright, I'll try it out in a few.
Btw, does this release have the custom master server thing or no?

**Comment by CrusoeDaWolf** [comment]
Welp, I can't get it to run. I copied over the extras or whatever. Do I need to get the vgui.dll from the Steam release?

> =================================================================================
	Xash3DEx 0.98 (build 3400) started at Dec11 2016 [18:55:59]
=================================================================================
Loading engine... - ok
FS_Init: done
FS_LoadGameInfo( valve )
FS_Rescan( Half-Life )
Adding packfile: valve/extras.pak (130 files)
Adding wadfile valve/cached.wad (2 files)
Adding wadfile valve/decals.wad (222 files)
Adding wadfile valve/fonts.wad (3 files)
Adding wadfile valve/gfx.wad (7 files)
Adding wadfile valve/halflife.wad (3116 files)
Adding wadfile valve/liquids.wad (32 files)
Adding wadfile valve/spraypaint.wad (14 files)
Adding wadfile valve/tempdecal.wad (1 files)
Adding wadfile valve/xeno.wad (264 files)
InitDecals: 222 decals
Sys_LoadLibrary: Loading wsock32.dll - ok
NET_Init()
Console initialized.
execing video.cfg
execing opengl.cfg
Sys_LoadLibrary: Loading opengl32.dll - ok
GL_CheckExtension: OpenGL Internal ProcAddress - enabled
Set: Mode 23: 16x9 [1600x900]
VID_ChoosePFD( color 24, alpha 8, depth 32, stencil 8 )
VID_ChoosePFD: using hardware acceleration
GL PFD: color( 32-bits ) alpha( 8-bits ) Z( 32-bit )
VID_StartupGamma: software gamma initialized
GL_CheckExtension: OpenGL 1.1.0 - enabled
Video: AMD Radeon HD 7700 Series
GL_CheckExtension: WGL_EXT_swap_control - enabled
GL_CheckExtension: glDrawRangeElements - enabled
GL_CheckExtension: GL_ARB_multitexture - enabled
GL_CheckExtension: GL_ARB_texture_env_combine - enabled
GL_CheckExtension: GL_ARB_texture_env_dot3 - enabled
GL_CheckExtension: GL_EXT_texture3D - enabled
GL_CheckExtension: GL_SGIS_generate_mipmap - enabled
GL_CheckExtension: GL_ARB_texture_cube_map - enabled
GL_CheckExtension: GL_ARB_seamless_cube_map - enabled
GL_CheckExtension: GL_EXT_point_parameters - enabled
GL_CheckExtension: GL_ARB_texture_non_power_of_two - enabled
GL_CheckExtension: GL_ARB_texture_compression - enabled
GL_CheckExtension: GL_EXT_compiled_vertex_array - enabled
GL_CheckExtension: GL_EXT_texture_edge_clamp - enabled
GL_CheckExtension: GL_EXT_texture_filter_anisotropic - enabled
GL_CheckExtension: GL_EXT_texture_lod_bias - enabled
GL_CheckExtension: GL_ARB_texture_border_clamp - enabled
GL_CheckExtension: GL_EXT_blend_minmax - enabled
GL_CheckExtension: GL_EXT_blend_subtract - enabled
GL_CheckExtension: glStencilOpSeparate - enabled
GL_CheckExtension: GL_EXT_stencil_two_side - failed
GL_CheckExtension: GL_ARB_vertex_buffer_object - enabled
GL_CheckExtension: GL_ARB_texture_env_add - enabled
GL_CheckExtension: GL_ARB_shader_objects - enabled
GL_CheckExtension: GL_ARB_shading_language_100 - enabled
GL_CheckExtension: GL_ARB_vertex_shader - enabled
GL_CheckExtension: GL_ARB_fragment_shader - enabled
GL_CheckExtension: GL_ARB_depth_texture - enabled
GL_CheckExtension: GL_ARB_shadow - enabled
GL_CheckExtension: GL_ARB_texture_float - enabled
GL_CheckExtension: GL_ARB_depth_buffer_float - enabled
GL_CheckExtension: GL_ARB_occlusion_query - enabled
GL_Upload: *white s&3 [1 x 1]
GL_Upload: *gray s&3 [1 x 1]
GL_Upload: *black s&3 [1 x 1]
GL_Upload: *vsdct s&3 [1 x 1]
SCR_Init()
Sys_LoadLibrary: Loading ../menu - ok
Sys_LoadLibrary: Loading avifil32.dll - ok
Sys_LoadLibrary: Loading msvfw32.dll - ok
Sys_LoadLibrary: Loading msacm32.dll - ok
AVI_Initailize: done
Sys_LoadLibrary: Loading ../vguiglue - failed
Error: Cannot load vguiglue lib!
Host_InitError: Failed to init vgui glue lib!

**Comment by Sh1ft0x0EF** [comment]
Not yet

Console option was removed from the menu as I remember now
You can access the console if you set developer to > 0 and press tilde
GS opens a console at dev >= 0 but current impl here requires dev > 0

**Comment by CrusoeDaWolf** [comment]
Ah. I just realized I can just press tilde in the menu now. It works!

**Comment by Sh1ft0x0EF** [comment]
UPD: reuploaded binaries for the latest release - added missing vgui.dll
About custom master server - I replaced hardcoded value to actual for so it can search for servers
