### ISSUE TITLE
Menu rendering issue

### ISSUE THREAD

**Issue by CrusoeDaWolf** [Sh1ft0x0EF/Xash3DEx#19]
http://www.mediafire.com/convkey/e962/7j4h5pg30al4wkdzg.jpg
This happens in the main menu when the game has a map loaded.

**Comment by Sh1ft0x0EF** [comment]
Yes, I know about that
It was in that shape for a while already
Current code assumes that if menu is open then it wraps all the screen and scene rendering can be skipped
I'll fix it soon along with some other bugs of that kind

**Comment by Sh1ft0x0EF** [comment]
Note: you can use gl_clear 1 for now - menu entries will be visible and scene not

**Comment by Sh1ft0x0EF** [comment]
Done
