### ISSUE TITLE
Make console accessible from dev 0

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [Sh1ft0x0EF/Xash3DEx#20]
It currently need to write a batch file with additional "-dev" arg to open the console
Access from dev 0 is more handy

**Comment by CrusoeDaWolf** [comment]
Agreed. This would be very useful!

**Comment by Sh1ft0x0EF** [comment]
Fixed this and #19 
You can download a new build (3415) from the latest release and apply it above 3412
